name: hy-nrepl tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Hy ${{ matrix.hy-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hy-version: ["0.29.0", "1.0.0", "1.1.0"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install hy==${{ matrix.hy-version }}
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # If building from source locally, ensure build backend is present
        if [ -f pyproject.toml ]; then python -m pip install setuptools wheel pytest; fi
    - name: Test with pytest
      run: |
        pytest tests -q
