name: hy-nrepl tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Hy ${{ matrix.hy-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hy-version: ["0.29.0", "1.0.0", "1.1.0"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install hy==${{ matrix.hy-version }}
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest tests
