jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: pypi
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
    steps:
      # retrieve your distributions here
      - run: python -m pip install -U build
      - run: python -m build # make dist/*.whl, *.tar.gz
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
